/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const Invoice: core.serialization.ObjectSchema<serializers.Invoice.Raw, MercoaApi.Invoice> =
    core.serialization.object({
        id: core.serialization.lazy(async () => (await import("../../..")).InvoiceId).optional(),
        status: core.serialization.string().optional(),
        amount: core.serialization.number().optional(),
        currency: core.serialization.string().optional(),
        dueDate: core.serialization.string().optional(),
        invoiceNumber: core.serialization.string().optional(),
        noteToSelf: core.serialization.string().optional(),
        createdAt: core.serialization.string().optional(),
        updatedAt: core.serialization.string().optional(),
        vendorId: core.serialization.string().optional(),
        vendor: core.serialization.lazyObject(async () => (await import("../../..")).Entity).optional(),
        payerId: core.serialization.string().optional(),
        payer: core.serialization.lazyObject(async () => (await import("../../..")).Entity).optional(),
        paymentSource: core.serialization.lazyObject(async () => (await import("../../..")).PaymentMethod).optional(),
        paymentSourceId: core.serialization.string().optional(),
        paymentDestination: core.serialization
            .lazyObject(async () => (await import("../../..")).PaymentMethod)
            .optional(),
        paymentDestinationId: core.serialization.string().optional(),
    });

export declare namespace Invoice {
    interface Raw {
        id?: serializers.InvoiceId.Raw | null;
        status?: string | null;
        amount?: number | null;
        currency?: string | null;
        dueDate?: string | null;
        invoiceNumber?: string | null;
        noteToSelf?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        vendorId?: string | null;
        vendor?: serializers.Entity.Raw | null;
        payerId?: string | null;
        payer?: serializers.Entity.Raw | null;
        paymentSource?: serializers.PaymentMethod.Raw | null;
        paymentSourceId?: string | null;
        paymentDestination?: serializers.PaymentMethod.Raw | null;
        paymentDestinationId?: string | null;
    }
}
