/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.invoice.getInvoices.Response.Raw, MercoaApi.Invoice[]> =
    core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Invoice));

export declare namespace Response {
    type Raw = serializers.Invoice.Raw[];
}
