/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.representative.getAll.Response.Raw,
    MercoaApi.Representative[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Representative));

export declare namespace Response {
    type Raw = serializers.Representative.Raw[];
}
