/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { MercoaApi } from "@fern-api/mercoa";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Client {
    interface Options {
        environment?: environments.MercoaApiEnvironment | string;
        token?: core.Supplier<core.BearerToken>;
    }
}

export class Client {
    constructor(private readonly options: Client.Options) {}

    /**
     * Find counterparties
     */
    public async find(
        entityId: MercoaApi.EntityId,
        request: MercoaApi.FindCounterpartiesRequest
    ): Promise<MercoaApi.Entity[]> {
        const _queryParams = new URLSearchParams();
        _queryParams.append("query", request.query);
        if (request.paymentMethods != null) {
            _queryParams.append("paymentMethods", request.paymentMethods.toString());
        }

        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/entity/${entityId}/counterparties/`
            ),
            method: "GET",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.counterparty.find.Response.parse(
                _response.body as serializers.counterparty.find.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
