/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { MercoaApi } from "@fern-api/mercoa";

export interface Entity {
    id?: MercoaApi.EntityId;
    accountType: string;
    name?: string;
    email?: string;
    profile: MercoaApi.Profile;
    moovStatus?: string;
    ownersProvided?: boolean;
    accpetedMoovTos?: boolean;
    createdAt?: string;
    updatedAt?: string;
}
