/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { MercoaApi } from "@fern-api/mercoa";

export interface IndividualProfile {
    email: string;
    phone: MercoaApi.PhoneNumber;
    name: MercoaApi.FullName;
    birthdate: MercoaApi.BirthDate;
    address: MercoaApi.Address;
}
