/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const BankAccount: core.serialization.ObjectSchema<serializers.BankAccount.Raw, MercoaApi.BankAccount> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        bankName: core.serialization.string(),
        accountName: core.serialization.string().optional(),
        routingNumber: core.serialization.string(),
        accountNumber: core.serialization.string(),
        accountType: core.serialization.string(),
        moovStatus: core.serialization.string(),
    });

export declare namespace BankAccount {
    interface Raw {
        id?: string | null;
        bankName: string;
        accountName?: string | null;
        routingNumber: string;
        accountNumber: string;
        accountType: string;
        moovStatus: string;
    }
}
