/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const Check: core.serialization.ObjectSchema<serializers.Check.Raw, MercoaApi.Check> = core.serialization.object(
    {
        id: core.serialization.string().optional(),
        payToTheOrderOf: core.serialization.string(),
        addressLine1: core.serialization.string(),
        addressLine2: core.serialization.string().optional(),
        city: core.serialization.string(),
        stateOrProvince: core.serialization.string(),
        postalCode: core.serialization.string(),
        country: core.serialization.string(),
    }
);

export declare namespace Check {
    interface Raw {
        id?: string | null;
        payToTheOrderOf: string;
        addressLine1: string;
        addressLine2?: string | null;
        city: string;
        stateOrProvince: string;
        postalCode: string;
        country: string;
    }
}
