/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { MercoaApi } from "@fern-api/mercoa";

export interface IndividualGovernmentId {
    ssn: MercoaApi.SocialSecurityNumber;
    itin: MercoaApi.Itin;
}
