/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { MercoaApi } from "@fern-api/mercoa";

export interface Representative {
    id?: MercoaApi.RepresentativeId;
    name: MercoaApi.FullName;
    phone: MercoaApi.PhoneNumber;
    email: string;
    address: MercoaApi.Address;
    birthDateProvided?: boolean;
    governmentIdProvided?: boolean;
    birthDate?: MercoaApi.BirthDate;
    governmentId?: MercoaApi.IndividualGovernmentId;
    responsibilities?: MercoaApi.Responsibilities;
    createdOn?: string;
    updatedOn?: string;
    disabledOn?: string;
}
