/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.paymentMethod.completeMicroDeposits.Request.Raw,
    MercoaApi.CompleteMicroDepositsRequest
> = core.serialization.object({
    amounts: core.serialization.list(core.serialization.number()).optional(),
});

export declare namespace Request {
    interface Raw {
        amounts?: number[] | null;
    }
}
