/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<serializers.paymentMethod.create.Request.Raw, MercoaApi.PaymentMethod> =
    core.serialization.lazyObject(async () => (await import("../../..")).PaymentMethod);

export declare namespace Request {
    type Raw = serializers.PaymentMethod.Raw;
}

export const Response: core.serialization.Schema<
    serializers.paymentMethod.create.Response.Raw,
    MercoaApi.PaymentMethod
> = core.serialization.lazyObject(async () => (await import("../../..")).PaymentMethod);

export declare namespace Response {
    type Raw = serializers.PaymentMethod.Raw;
}
