/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.paymentMethod.get.Response.Raw, MercoaApi.PaymentMethod> =
    core.serialization.lazyObject(async () => (await import("../../..")).PaymentMethod);

export declare namespace Response {
    type Raw = serializers.PaymentMethod.Raw;
}
