/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.entity.get.Response.Raw, MercoaApi.Entity> =
    core.serialization.lazyObject(async () => (await import("../../..")).Entity);

export declare namespace Response {
    type Raw = serializers.Entity.Raw;
}
