/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FindCounterpartiesRequest {
    /**
     * Search term
     */
    query: string;
    /**
     * include payment method information in response
     */
    paymentMethods?: boolean;
}
