/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const Itin: core.serialization.ObjectSchema<serializers.Itin.Raw, MercoaApi.Itin> = core.serialization.object({
    full: core.serialization.string(),
    lastFour: core.serialization.string(),
});

export declare namespace Itin {
    interface Raw {
        full: string;
        lastFour: string;
    }
}
