/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const Representative: core.serialization.ObjectSchema<serializers.Representative.Raw, MercoaApi.Representative> =
    core.serialization.object({
        id: core.serialization.lazy(async () => (await import("../../..")).RepresentativeId).optional(),
        name: core.serialization.lazyObject(async () => (await import("../../..")).FullName),
        phone: core.serialization.lazyObject(async () => (await import("../../..")).PhoneNumber),
        email: core.serialization.string(),
        address: core.serialization.lazyObject(async () => (await import("../../..")).Address),
        birthDateProvided: core.serialization.boolean().optional(),
        governmentIdProvided: core.serialization.property(
            "governmentIDProvided",
            core.serialization.boolean().optional()
        ),
        birthDate: core.serialization.lazyObject(async () => (await import("../../..")).BirthDate).optional(),
        governmentId: core.serialization.property(
            "governmentID",
            core.serialization.lazyObject(async () => (await import("../../..")).IndividualGovernmentId).optional()
        ),
        responsibilities: core.serialization
            .lazyObject(async () => (await import("../../..")).Responsibilities)
            .optional(),
        createdOn: core.serialization.string().optional(),
        updatedOn: core.serialization.string().optional(),
        disabledOn: core.serialization.string().optional(),
    });

export declare namespace Representative {
    interface Raw {
        id?: serializers.RepresentativeId.Raw | null;
        name: serializers.FullName.Raw;
        phone: serializers.PhoneNumber.Raw;
        email: string;
        address: serializers.Address.Raw;
        birthDateProvided?: boolean | null;
        governmentIDProvided?: boolean | null;
        birthDate?: serializers.BirthDate.Raw | null;
        governmentID?: serializers.IndividualGovernmentId.Raw | null;
        responsibilities?: serializers.Responsibilities.Raw | null;
        createdOn?: string | null;
        updatedOn?: string | null;
        disabledOn?: string | null;
    }
}
