/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const RepresentativeId: core.serialization.Schema<serializers.RepresentativeId.Raw, MercoaApi.RepresentativeId> =
    core.serialization.string();

export declare namespace RepresentativeId {
    type Raw = string;
}
