/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const SocialSecurityNumber: core.serialization.ObjectSchema<
    serializers.SocialSecurityNumber.Raw,
    MercoaApi.SocialSecurityNumber
> = core.serialization.object({
    full: core.serialization.string(),
    lastFour: core.serialization.string(),
});

export declare namespace SocialSecurityNumber {
    interface Raw {
        full: string;
        lastFour: string;
    }
}
