/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const BusinessProfile: core.serialization.ObjectSchema<
    serializers.BusinessProfile.Raw,
    MercoaApi.BusinessProfile
> = core.serialization.object({
    email: core.serialization.string(),
    phone: core.serialization.lazyObject(async () => (await import("../../..")).PhoneNumber),
    businessType: core.serialization.string(),
    legalBusinessName: core.serialization.string(),
    doingBusinessAs: core.serialization.string(),
    website: core.serialization.string(),
    ownersProvided: core.serialization.boolean(),
    taxId: core.serialization.lazyObject(async () => (await import("../../..")).TaxId),
    address: core.serialization.lazyObject(async () => (await import("../../..")).Address),
});

export declare namespace BusinessProfile {
    interface Raw {
        email: string;
        phone: serializers.PhoneNumber.Raw;
        businessType: string;
        legalBusinessName: string;
        doingBusinessAs: string;
        website: string;
        ownersProvided: boolean;
        taxId: serializers.TaxId.Raw;
        address: serializers.Address.Raw;
    }
}
