/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const IndividualProfile: core.serialization.ObjectSchema<
    serializers.IndividualProfile.Raw,
    MercoaApi.IndividualProfile
> = core.serialization.object({
    email: core.serialization.string(),
    phone: core.serialization.lazyObject(async () => (await import("../../..")).PhoneNumber),
    name: core.serialization.lazyObject(async () => (await import("../../..")).FullName),
    birthdate: core.serialization.lazyObject(async () => (await import("../../..")).BirthDate),
    address: core.serialization.lazyObject(async () => (await import("../../..")).Address),
});

export declare namespace IndividualProfile {
    interface Raw {
        email: string;
        phone: serializers.PhoneNumber.Raw;
        name: serializers.FullName.Raw;
        birthdate: serializers.BirthDate.Raw;
        address: serializers.Address.Raw;
    }
}
