/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { MercoaApi } from "@fern-api/mercoa";

export interface Invoice {
    id?: MercoaApi.InvoiceId;
    status?: string;
    amount?: number;
    currency?: string;
    dueDate?: string;
    invoiceNumber?: string;
    noteToSelf?: string;
    createdAt?: string;
    updatedAt?: string;
    vendorId?: string;
    vendor?: MercoaApi.Entity;
    payerId?: string;
    payer?: MercoaApi.Entity;
    paymentSource?: MercoaApi.PaymentMethod;
    paymentSourceId?: string;
    paymentDestination?: MercoaApi.PaymentMethod;
    paymentDestinationId?: string;
}
