/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BankAccount {
    id?: string;
    bankName: string;
    accountName?: string;
    routingNumber: string;
    accountNumber: string;
    accountType: string;
    moovStatus: string;
}
