/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { MercoaApi } from "@fern-api/mercoa";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Client {
    interface Options {
        environment?: environments.MercoaApiEnvironment | string;
        token?: core.Supplier<core.BearerToken>;
    }
}

export class Client {
    constructor(private readonly options: Client.Options) {}

    /**
     * Get all entities
     */
    public async getAll(): Promise<MercoaApi.Entity[]> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment ?? environments.MercoaApiEnvironment.Production, "/entities"),
            method: "GET",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return await serializers.entity.getAll.Response.parse(
                _response.body as serializers.entity.getAll.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async create(request: MercoaApi.Entity): Promise<MercoaApi.Entity> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment ?? environments.MercoaApiEnvironment.Production, "/entity"),
            method: "POST",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
            body: await serializers.entity.create.Request.json(request),
        });
        if (_response.ok) {
            return await serializers.entity.create.Response.parse(
                _response.body as serializers.entity.create.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Get entity
     */
    public async get(entityId: MercoaApi.EntityId): Promise<MercoaApi.Entity> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/entity/${entityId}`
            ),
            method: "GET",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return await serializers.entity.get.Response.parse(_response.body as serializers.entity.get.Response.Raw);
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Update entity
     */
    public async update(entityId: MercoaApi.EntityId, request: MercoaApi.Entity): Promise<MercoaApi.Entity> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/entity/${entityId}`
            ),
            method: "POST",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
            body: await serializers.entity.update.Request.json(request),
        });
        if (_response.ok) {
            return await serializers.entity.update.Response.parse(
                _response.body as serializers.entity.update.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Delete entity
     */
    public async delete(entityId: MercoaApi.EntityId): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/entity/${entityId}`
            ),
            method: "DELETE",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * End user accepts Terms of Service
     */
    public async acceptTermsOfService(entityId: MercoaApi.EntityId): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/entity/${entityId}/accept-tos`
            ),
            method: "POST",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
