/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { MercoaApi } from "@fern-api/mercoa";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Client {
    interface Options {
        environment?: environments.MercoaApiEnvironment | string;
        token?: core.Supplier<core.BearerToken>;
    }
}

export class Client {
    constructor(private readonly options: Client.Options) {}

    /**
     * Get representatives for an entity
     */
    public async getAll(entityId: MercoaApi.EntityId): Promise<MercoaApi.Representative[]> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/api/entity/${entityId}/representatives`
            ),
            method: "GET",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return await serializers.representative.getAll.Response.parse(
                _response.body as serializers.representative.getAll.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Create representative
     */
    public async create(
        entityId: MercoaApi.EntityId,
        request: MercoaApi.Representative
    ): Promise<MercoaApi.Representative> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/api/entity/${entityId}/representative`
            ),
            method: "POST",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
            body: await serializers.representative.create.Request.json(request),
        });
        if (_response.ok) {
            return await serializers.representative.create.Response.parse(
                _response.body as serializers.representative.create.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Get representative
     */
    public async get(
        entityId: MercoaApi.EntityId,
        representativeId: MercoaApi.RepresentativeId
    ): Promise<MercoaApi.Representative> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/api/entity/${entityId}/representative/${representativeId}`
            ),
            method: "GET",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return await serializers.representative.get.Response.parse(
                _response.body as serializers.representative.get.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Delete representative
     */
    public async delete(entityId: MercoaApi.EntityId, representativeId: MercoaApi.RepresentativeId): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/api/entity/${entityId}/representative/${representativeId}`
            ),
            method: "DELETE",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
