/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { MercoaApi } from "@fern-api/mercoa";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Client {
    interface Options {
        environment?: environments.MercoaApiEnvironment | string;
        token?: core.Supplier<core.BearerToken>;
    }
}

export class Client {
    constructor(private readonly options: Client.Options) {}

    public async getAll(
        entityId: MercoaApi.EntityId,
        request: MercoaApi.GetAllPaymentMethodsRequest
    ): Promise<MercoaApi.PaymentMethod[]> {
        const _queryParams = new URLSearchParams();
        _queryParams.append("type", request.type);
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/entity/${entityId}/paymentMethods`
            ),
            method: "GET",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.paymentMethod.getAll.Response.parse(
                _response.body as serializers.paymentMethod.getAll.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Create payment method
     */
    public async create(
        entityId: MercoaApi.EntityId,
        request: MercoaApi.PaymentMethod
    ): Promise<MercoaApi.PaymentMethod> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/entity/${entityId}/paymentMethod`
            ),
            method: "POST",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
            body: await serializers.paymentMethod.create.Request.json(request),
        });
        if (_response.ok) {
            return await serializers.paymentMethod.create.Response.parse(
                _response.body as serializers.paymentMethod.create.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Get payment method
     */
    public async get(
        entityId: MercoaApi.EntityId,
        paymentMethodId: MercoaApi.PaymentMethodId
    ): Promise<MercoaApi.PaymentMethod> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/entity/${entityId}/paymentMethod/${paymentMethodId}`
            ),
            method: "GET",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return await serializers.paymentMethod.get.Response.parse(
                _response.body as serializers.paymentMethod.get.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Delete payment method
     */
    public async delete(entityId: MercoaApi.EntityId, paymentMethodId: MercoaApi.PaymentMethodId): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/entity/${entityId}/paymentMethod/${paymentMethodId}`
            ),
            method: "DELETE",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Initiate micro deposits for a bank account
     */
    public async initiateMicroDeposits(
        entityId: MercoaApi.EntityId,
        paymentMethodId: MercoaApi.PaymentMethodId
    ): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/entity/${entityId}/paymentMethod/${paymentMethodId}/micro-deposits`
            ),
            method: "POST",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Complete micro deposit verification
     */
    public async completeMicroDeposits(
        entityId: MercoaApi.EntityId,
        paymentMethodId: MercoaApi.PaymentMethodId,
        request?: MercoaApi.CompleteMicroDepositsRequest
    ): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.MercoaApiEnvironment.Production,
                `/entity/${entityId}/paymentMethod/${paymentMethodId}/micro-deposits`
            ),
            method: "PUT",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
            body: await serializers.paymentMethod.completeMicroDeposits.Request.json({
                amounts: request?.amounts,
            }),
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.MercoaApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MercoaApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.MercoaApiTimeoutError();
            case "unknown":
                throw new errors.MercoaApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
