/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as CounterpartyClient } from "./api/resources/counterparty/client/Client";
import { Client as EntityClient } from "./api/resources/entity/client/Client";
import { Client as InvoiceClient } from "./api/resources/invoice/client/Client";
import { Client as PaymentMethodClient } from "./api/resources/paymentMethod/client/Client";
import { Client as RepresentativeClient } from "./api/resources/representative/client/Client";

export declare namespace MercoaApiClient {
    interface Options {
        environment?: environments.MercoaApiEnvironment | string;
        token?: core.Supplier<core.BearerToken>;
    }
}

export class MercoaApiClient {
    constructor(private readonly options: MercoaApiClient.Options) {}

    #counterparty: CounterpartyClient | undefined;

    public get counterparty(): CounterpartyClient {
        return (this.#counterparty ??= new CounterpartyClient(this.options));
    }

    #entity: EntityClient | undefined;

    public get entity(): EntityClient {
        return (this.#entity ??= new EntityClient(this.options));
    }

    #invoice: InvoiceClient | undefined;

    public get invoice(): InvoiceClient {
        return (this.#invoice ??= new InvoiceClient(this.options));
    }

    #paymentMethod: PaymentMethodClient | undefined;

    public get paymentMethod(): PaymentMethodClient {
        return (this.#paymentMethod ??= new PaymentMethodClient(this.options));
    }

    #representative: RepresentativeClient | undefined;

    public get representative(): RepresentativeClient {
        return (this.#representative ??= new RepresentativeClient(this.options));
    }
}
