/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const MercoaApiEnvironment = {
    Production: "https://www.mercoa.com/api",
} as const;

export type MercoaApiEnvironment = typeof MercoaApiEnvironment.Production;
