/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const BirthDate: core.serialization.ObjectSchema<serializers.BirthDate.Raw, MercoaApi.BirthDate> =
    core.serialization.object({
        day: core.serialization.number().optional(),
        month: core.serialization.number().optional(),
        year: core.serialization.number().optional(),
    });

export declare namespace BirthDate {
    interface Raw {
        day?: number | null;
        month?: number | null;
        year?: number | null;
    }
}
