/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { MercoaApi } from "@fern-api/mercoa";
import * as core from "../../../../core";

export const PhoneNumber: core.serialization.ObjectSchema<serializers.PhoneNumber.Raw, MercoaApi.PhoneNumber> =
    core.serialization.object({
        countryCode: core.serialization.string(),
        number: core.serialization.string(),
    });

export declare namespace PhoneNumber {
    interface Raw {
        countryCode: string;
        number: string;
    }
}
